[package]
name = "ddnsv6"
version = "1.0.0"
authors = ["DosGo <dosgo@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.2", features = ["blocking","json"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
async-std = { version = "1.9.0" ,default-features = true, features = ["std"]}
get_if_addrs = {version="0.5.3"}
cidr-utils={version="0.5.4"}
clap = { version = "2.32.0", features = ["yaml"] }
trust-dns-resolver = {version="0.11.0"}
[profile.release]
lto = true